import Head from "next/head";
import Image from "next/image";
import Link from "next/Link";
import { Inter } from "@next/font/google";
//import styles from "../styles/Home.module.css";
import { HomePage } from "../src/home/home-page";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Online Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomePage data={data} />
    </>
  );
}

export async function getServerSideProps() {
  try {
    const response = await axios.get("//localhost:3000/api/get-events");
    return {
      props: {
        data: response.data.rows,
      },
    };
  } catch {
    return {
      props: {},
    };
  }
}
